# One-Sample t-test

**one-sample t-test:** Compare your sample mean to a known test value. For example, to compare your sample IQ to the population norm of 100.

## The Worked Example

```{r we, echo = FALSE}
set.seed(1410)

mx <- runif(1, 0, 100) %>% round2(2)
sdx <- runif(1, 0, 5) %>% round2(2)
N <- seq(10, 100, 2) %>% sample(1)

dat <- tibble(Group = rep(c("A","B"), each = N/2),
              scores = rnorm(N, mx, sdx)) %>%
  mutate(scores = scores + rep(c(0,2), each = N/2))

desc <- dat %>% 
  group_by(Group) %>%
  summarise(Npg = n(),
            Means = mean(scores) %>% round2(2),
            SDs = sd(scores) %>% round2(2),
            Variance = var(scores) %>% round2(2),
            `Standard Err.` = (SDs/sqrt(Npg)) %>% round2(2))

sdp <- sqrt((((N/2 - 1) * desc$SDs[1]^2) + ((N/2 - 1) * desc$SDs[2]^2))/(N/2 + N/2 - 2))

t.value <- ((desc$Means[1] - desc$Means[2])/(sdp * sqrt(((1/(N/2)) + (1/(N/2)))))) %>% round2(2)            

cohensd <- ((2* t.value)/sqrt(N-2)) %>% round2(2)

results <- t.test(dat %>% filter(Group == "A") %>% pull(scores), 
                  dat %>% filter(Group == "B") %>% pull(scores), 
                  var.equal = TRUE) %>% 
  tidy() %>%
  mutate(cohensd_t = (2*statistic)/sqrt(parameter))


# one-sample
iq_mean <- 110
iq_sd <- 7.5
iq_n <- 25
crit_mean <- 100
tval <- (iq_mean  - crit_mean)/(iq_sd/sqrt(iq_n))
dval <- round2(tval,2)/sqrt(iq_n)
dfval <- iq_n - 1 

```

The formula is as follows:

$$t = \frac{\bar{x} - \mu}{\frac{s}{\sqrt{n}}}$$
And you can translate the symbols as:

* $\bar{x}$ is the mean value of your sample of interest
* $\mu$ is the test value to compare against (also called the **criterion value**)
* $s$ is the standard deviation of your sample of interest
* $n$ is the number of observations (e.g. participants) in your sample of interest

So for example, if we had a sample of 25 people, and we knew that the mean and standard deviation of the IQ of was M = 110, SD = 7.5, and that we wanted to compare that sample to a criterion value of $\mu$ = 100, then we would do the following:

$$t = \frac{`r iq_mean`  - `r crit_mean`}{\frac{`r iq_sd`}{\sqrt{`r iq_n`}}}$$

And if we do the top half of the formula first, that becomes:

$$t = \frac{`r iq_mean  - crit_mean`}{\frac{`r iq_sd`}{\sqrt{`r iq_n`}}}$$

And then start to complete the bottom half by taking the sqaure root of n first, (i.e. $\sqrt{n}$), we get:

$$t = \frac{`r iq_mean  - crit_mean`}{\frac{`r iq_sd`}{`r sqrt(iq_n)`}}$$
And so if we then complete the bottom half by dividing the standard deviation of the sample ($s$) by the square root of n ($\sqrt{n}$), we get:

$$t = \frac{`r iq_mean  - crit_mean`}{`r iq_sd/sqrt(iq_n)`}$$

And finally, if we divide the top half of the formula by the bottom half we get:

$$t = \frac{`r iq_mean  - crit_mean`}{`r iq_sd/sqrt(iq_n)`} = `r (iq_mean  - crit_mean)/(iq_sd/sqrt(iq_n))`$$

Giving us a t-value of t = `r tval` which we can round to two decimal places, giving us t = `r round2(tval,2)`

## Degrees of Freedom

The degrees of freedom in a one-sample t-test is calculated as:

$$df = N - 1$$

And if we know that we have `r  iq_n` participants in our sample then we get:

$$df = N - 1 = `r  iq_n` - 1 = `r  iq_n - 1`$$

Giving us $df$ = `r dfval`

## Effect Size

A common effect size used for t-test is Cohen's d. The formula for the effect size, in of a one-sample t-test, if you only know the t-value and the number of participants is:

$$d = \frac{t}{\sqrt{N}}$$

And here we know that:

* $t$ = `r round2(tval,2)`
* $N$ = `r iq_n`

Which if we put those into the formula we get:

$$d = \frac{`r round2(tval,2)`}{\sqrt{`r iq_n`}}$$
And if we resolve the bottom half first:

$$d = \frac{`r round2(tval,2)`}{`r sqrt(iq_n)`}$$

And then divide the top by the bottom we get:

$$d = \frac{`r round2(tval,2)`}{`r sqrt(iq_n)`} = `r round2(tval,2)/sqrt(iq_n)`$$

Giving us an effect size of $d$ = `r round2(dval,2)`, rounded to two decimal places.

## Write-up

If we were to look at a critical values look-up table for $df = `r dfval`$ and $\alpha = .05$ (two-tailed), we would see that the critical value is $t_{crit} = `r qt(1 - .975, dfval, lower.tail = FALSE) %>% round2(3)`$. 

Given that our t-value, ignoring polarity and just looking at the absolute value, so $t = `r abs(round2(tval,2))`$, is `r ifelse(abs(tval) >= qt(1-.975, dfval, lower.tail = FALSE), "equal to or larger than", "smaller than")` our $t_{crit}$ then we can say our result is `r ifelse(abs(tval) >= qt(1-.975, dfval, lower.tail = FALSE), "significant", "non-significant")`, and as such would be written up as t(`r dfval`) = `r abs(round2(tval,2))`,`r ifelse(abs(tval) >= qt(1-.975, dfval, lower.tail = FALSE), " p < .05", " p > .05")`, d = `r round2(dval,2)`

## Look-Up table

Remembering that the $t_{crit}$ value is the smallest t-value you need to find a significant effect, find the $t_{crit}$ for your df, assuming $\alpha = .05$. If the $t$ value you calculated is equal to or larger than $t_{crit}$ then your test is significant.

|df | $\alpha = .05$|
|:-:|:-------------:|
|1  |`r qt(1-.975, 1, lower.tail = FALSE) %>% round2(3)`|
|2  |`r qt(1-.975, 2, lower.tail = FALSE) %>% round2(3)`|
|3  |`r qt(1-.975, 3, lower.tail = FALSE) %>% round2(3)`|
|4  |`r qt(1-.975, 4, lower.tail = FALSE) %>% round2(3)`|
|5  |`r qt(1-.975, 5, lower.tail = FALSE) %>% round2(3)`|
|6  |`r qt(1-.975, 6, lower.tail = FALSE) %>% round2(3)`|
|7  |`r qt(1-.975, 7, lower.tail = FALSE) %>% round2(3)`|
|8  |`r qt(1-.975, 8, lower.tail = FALSE) %>% round2(3)`|
|9  |`r qt(1-.975, 9, lower.tail = FALSE) %>% round2(3)`|
|10 |`r qt(1-.975, 10, lower.tail = FALSE) %>% round2(3)`|
|15 |`r qt(1-.975, 15, lower.tail = FALSE) %>% round2(3)`|
|20 |`r qt(1-.975, 20, lower.tail = FALSE) %>% round2(3)`|
|30 |`r qt(1-.975, 30, lower.tail = FALSE) %>% round2(3)`|
|40 |`r qt(1-.975, 40, lower.tail = FALSE) %>% round2(3)`|
|50 |`r qt(1-.975, 50, lower.tail = FALSE) %>% round2(3)`|
|60 |`r qt(1-.975, 60, lower.tail = FALSE) %>% round2(3)`|
|70 |`r qt(1-.975, 70, lower.tail = FALSE) %>% round2(3)`|
|80 |`r qt(1-.975, 80, lower.tail = FALSE) %>% round2(3)`|
|90 |`r qt(1-.975, 90, lower.tail = FALSE) %>% round2(3)`|
|100|`r qt(1-.975, 100, lower.tail = FALSE) %>% round2(3)`|