# Spearman Correlation

**The Spearman correlation** otherwise known as the Spearman rank correlation coefficient measures the relationship between two variables when that relationship is monotonic. It can be used for relationships that are linear or non-linear. 

As in the Pearson Correlation, the Spearman correlation measures the covariance between two variables, or the shared variance, and then standardises that measure between the values of -1 and 1 with -1 being the perfect negative relationship and 1 being the perfect positive relationship.

The key difference between the Spearman Correlation and the Pearson Correlation is that the Spearman Correlation is based on the rank order of data - i.e. the raw data is converted to ordinal ranks.

If all of the ranks within each variable are unique - i.e. there are no `r glossary("tied ranks", def = "when two or more values/observations within a variable are identical and assume the same rank order value", display = "tied ranks", link = FALSE)` - then the formula for the Spearman Correlation is as follows:

$$\rho = 1 - \frac{6 \times \sum{d_i^2}}{n(n^2-1)}$$

## Section glossary

```{r gloss-tab, echo=FALSE, results='asis'}

glossary_table()
```

